branding:
  appName: "MobileFactory Chat"
  logoPath: "/logo-c.svg"
  logoWidth: 28
  logoHeight: 28
  description: "모바일팩토리 챗봇에게 무엇이든 물어보세요."
  fullDescription: "/full-description.md"

buttons:
  enableFileUpload: false
  showAssistantSelector: false
  showToolCallToggle: false
  chatInputPlaceholder: "궁금한 내용을 물어보세요."

threads:
  showHistory: true
  enableDeletion: true
  enableTitleEdit: true
  autoGenerateTitles: true
  sidebarOpenByDefault: true

theme:
  fontFamily: "serif"
  fontSize: "large"
  colorScheme: "light"

ui:
  autoCollapseToolCalls: false
  chatWidth: "default"
